FROM almalinux:9


# while executing give below cli:
#     docker build -t from:v1 . It creates image of name repository == from, Tag == v1
# it will create only image with name from:v1, wont create any containers