FROM almalinux:9
LABEL employee="mohansai" \
      company="infosys" \
      course="devops"


# docker build -t label:v1 . ---> it will create an image of name lable:v1 by having the metadata added to it.

# when you are filtering the images using these any of the filters, then it will display respective image:
#     docker images -f 'label=company=infosys'   -> -f or --filter is filter option

# to check all filters, can use docker inspect imageid