FROM almalinux:9
#CMD ["ping", "google.com"]
ENTRYPOINT ["ping", "google.com"]





# CMD Command can be overridden at run time by giving as below:
#     after build
#     docker run -d entry:v1 ping yahoo.com ----> it will ping yahoo.com instead of google.com as it is overridden.
