FROM almalinux:9
RUN dnf install nginx -y


# while executing give below cli:
#     docker build -t run:v1 . It creates image of name repository == run, Tag == v1 and will install nginx service in this image
# it will creates image with name run:v1, wont create any containers