FROM onbuild:v1
#Aa nginx is installed and started in this created/customized base image onbuild:v1, it will do that automatically, but need to keep index.html file.




# 316  17/10/24 13:11:52 docker build -t test_build:v1 .
# 317  17/10/24 13:11:56 docker images
# 321  17/10/24 13:14:02 docker run -d -p 80:80 test_build:v1
# now open the server ip in browser as ip:80 ---> this will display index.html content
# 322  17/10/24 13:14:06 docker ps
