FROM almalinux:9
ENV employee="mohansai" \
    course="devops" \
    company="infosys"



    # docker build -t env:v1 .
    # 50  16/10/24 17:38:11 docker images
    # 54  16/10/24 17:38:59 docker ps
    # 56  16/10/24 17:39:46 docker run -d env:v1 sleep 100 ---> so that it will create a container env:v1 which runs 100 sec and after that will be exited(stopped running)
    # 57  16/10/24 17:39:49 docker ps
    # login to container ----> docker exec -it b6 bash
    # now give env, there it will show the environment variables usually set by developers.
    
    # This we used for mysql host and while giving password to mysql db